/**
 * Purpose: render the collected notices as one plain-text file — the
 * `THIRD_PARTY_LICENSES.txt` the app bundles and Settings → About opens.
 *
 * Deterministic by construction: every list is sorted by code unit (never by
 * locale), identical texts are printed once with every package that shares
 * them, and nothing time- or machine-dependent (dates, absolute paths, the app
 * version) is written. Regenerating an unchanged tree yields the same bytes,
 * so a diff of this file is a diff of the dependency licenses.
 *
 * @coordinates-with scripts/lib/thirdPartyLicenses.mjs — produces the inputs
 * @coordinates-with scripts/gen-third-party-licenses.test.mjs — the self-test
 * @module scripts/lib/thirdPartyLicensesRender
 */
import { byCodeUnit } from "./thirdPartyLicenses.mjs";

const RULE = "=".repeat(78);
const THIN = "-".repeat(78);

function section(title) {
  return [RULE, title, RULE, ""];
}

/** npm entries grouped by their exact text blocks, each group's members sorted. */
function groupNpm(entries) {
  const groups = new Map();
  for (const e of entries) {
    const body = e.texts.map((t) => (e.texts.length > 1 ? `[${t.file}]\n${t.text}` : t.text)).join("\n\n");
    const groupKey = `${e.source ?? ""}\u0000${body}`;
    const group = groups.get(groupKey) ?? { body, source: e.source, members: [] };
    group.members.push(`${e.name} ${e.version} (${e.license})`);
    groups.set(groupKey, group);
  }
  return [...groups.values()]
    .map((g) => ({ ...g, members: [...g.members].sort(byCodeUnit) }))
    .sort((a, b) => byCodeUnit(a.members[0], b.members[0]));
}

/**
 * @param {object} input
 * @param {{license: string, text: string, users: string[]}[]} input.rust
 * @param {{name: string, version: string, license: string, source: string|null, texts: {file: string, text: string}[]}[]} input.npm
 * @param {{component: string, version: string, license: string, host: {name: string, version: string}, embeddedIn?: string, source: string, text: string}[]} input.embedded
 *   `embeddedIn` replaces the default "compiled into <host>" where that would mislead
 * @returns {string}
 */
export function renderNotices({ rust, npm, embedded }) {
  const rustGroups = [...rust]
    .map((g) => ({ ...g, users: [...g.users].sort(byCodeUnit) }))
    .sort((a, b) => byCodeUnit(a.license, b.license) || byCodeUnit(a.users[0], b.users[0]));
  const crateCount = new Set(rustGroups.flatMap((g) => g.users)).size;
  const npmGroups = groupNpm(npm);
  const components = [...embedded].sort((a, b) => byCodeUnit(a.component, b.component));

  const out = [
    "THIRD-PARTY SOFTWARE NOTICES — VMark",
    "",
    "VMark includes the third-party software listed below. Each component is",
    "used under the license reproduced with it; those licenses require that",
    "their notices accompany every copy of VMark.",
    "",
    "Generated by scripts/gen-third-party-licenses.mjs. Do not edit by hand.",
    "",
    `Rust crates: ${crateCount}`,
    `npm packages: ${npm.length}`,
    `Embedded components: ${components.length}`,
    "",
  ];

  out.push(...section("1. Rust crates"));
  for (const g of rustGroups) {
    out.push(THIN, g.license, "Used by:", ...g.users, "", g.text, "");
  }

  out.push(...section("2. npm packages"));
  for (const g of npmGroups) {
    out.push(THIN, ...g.members);
    if (g.source) out.push(`Source: ${g.source}`);
    out.push("", g.body, "");
  }

  out.push(...section("3. Components embedded in bundled packages"));
  for (const c of components) {
    out.push(
      THIN,
      `${c.component} ${c.version} (${c.license}), ${c.embeddedIn ?? `compiled into ${c.host.name} ${c.host.version}`}`,
      `Source: ${c.source}`,
      "",
      c.text,
      "",
    );
  }

  return `${out.join("\n").replace(/\n+$/, "")}\n`;
}
